### ISSUE TITLE
add Rick Rolling

### ISSUE THREAD

**Issue by sp-team-jarvis** [cpradio/sp-team-jarvis#71]
_submitted by jeffreylees_

**Comment by jeffreylees** [comment]
When asked to "youtube me" occasionally jarvis responds with 

https://www.youtube.com/watch?v=oHg5SJYRHA0
https://youtu.be/oHg5SJYRHA0
https://goo.gl/RfBgeQ

Not sure if you can do a percentage equation? 10% of the time, or something?

**Comment by cpradio** [comment]
this is just evil. lol
