### ISSUE TITLE
ninja'd

### ISSUE THREAD

**Issue by sp-team-jarvis** [cpradio/sp-team-jarvis#87]
_submitted by jeffreylees_

**Comment by jeffreylees** [comment]
response to "ninja" "ninjad" "ninja'd"

http://i.imgur.com/ueIz8hM.png
http://www.urbandictionary.com/render_definition.php?defid=1489876
https://c1.staticflickr.com/3/2533/3967014086_ddc4536b4a.jpg
http://pinkie.mylittlefacewhen.com/media/f/rsz/mlfw4912_medium.jpg
