### ISSUE TITLE
c-c-combo breaker img

### ISSUE THREAD

**Issue by sp-team-jarvis** [cpradio/sp-team-jarvis#88]
_submitted by ryanreese09_

**Comment by jeffreylees** [comment]
https://i.ytimg.com/vi/9l2S4g603HI/hqdefault.jpg
https://i.ytimg.com/vi/vY6aJKki3AM/hqdefault.jpg
http://cf.chucklesnetwork.agj.co/items/3/3/7/1/1/c-c-combo-breaker-success.jpg
